// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concrete;

#nullable disable

namespace StoreApp.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240307234504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("StoreApp.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "",
                            Description = "Nice part",
                            Name = "Product v11",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 2,
                            Category = "",
                            Description = "Nice part 12",
                            Name = "Product v12",
                            Price = 2300m
                        },
                        new
                        {
                            Id = 3,
                            Category = "",
                            Description = "Nice part 13",
                            Name = "Product v13",
                            Price = 3300m
                        },
                        new
                        {
                            Id = 4,
                            Category = "",
                            Description = "Nice part 14",
                            Name = "Product v14",
                            Price = 4300m
                        },
                        new
                        {
                            Id = 5,
                            Category = "",
                            Description = "Nice part 15",
                            Name = "Product v15",
                            Price = 5300m
                        },
                        new
                        {
                            Id = 6,
                            Category = "",
                            Description = "Nice part 16",
                            Name = "Product v16",
                            Price = 6300m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
